# Generated by Django 5.0.2 on 2024-03-15 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_bio',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(255, 'requirement: at least 255 characters')]),
        ),
    ]
